### ISSUE TITLE
Change package name to uwu-theme

### ISSUE THREAD

**Issue by martenlienen** [kborling/uwu.el#2]
Hey,
thank you for this nice theme. I just tried installing it via straight.el and it is a bit more difficult that it needs to be because the package is called uwu instead of the conventional uwu-theme and `uwu-theme.el`. This leads to errors when you `require` the theme or load it via `load-theme`.

Best,
Marten

**Comment by kborling** [comment]
Thank you for the suggestion. I renamed `uwu.el` to `uwu-theme.el` and fixed a few issues with the file header as well. Can you let me know if this resolves the issues with `straight.el`? If not, could you share the errors that you are getting? I'll get straight setup tomorrow on my machine to test with it going forward.

**Comment by movedtocodeberg** [comment]
Hello, just checking in to confirm uwu now installs and loads as expected using `straight.el`

```
(straight-use-package
 '(uwu-theme :host github :repo "kborling/uwu.el"))
(require 'uwu-theme)
(load-theme 'uwu t)
```

**Comment by kborling** [comment]
I’ll add that to the Readme. Thanks

**Comment by martenlienen** [comment]
Works for me too with the use-package configuration
```elisp
(use-package uwu-theme
  :straight (uwu-theme :host github :repo "kborling/uwu.el")
  :config (load-theme 'uwu t))
```
Would it make sense to also rename the repo to uwu-theme.el? github sets up a redirect, so existing installations similar to mine keep working.

**Comment by kborling** [comment]
> Would it make sense to also rename the repo to uwu-theme.el? github sets up a redirect, so existing installations similar to mine keep working.

Thanks for the suggestion. I've been thinking about renaming the repo and I think it makes sense to do it. I didn't realize Github will handle the redirect, so that will make things easy. I'll go ahead and rename the repo to `uwu-theme.el`.
