### ISSUE TITLE
Changing the name of colorscheme.

### ISSUE THREAD

**Issue by mngshm** [kborling/uwu.el#6]
Hey Kborling, Recently UwU got some updates with the colors and its name. You can the palette ![here](https://github.com/Mangeshrex/everblush.vim) and apply the changes according to it. Also the name has changed from UwU to Everblush. I hope you would apply the changes soon so that I can add this repo link into the vim repo readme. Once you're done with it please let me know :)  

Thank You,

**Comment by kborling** [comment]
I'll take a look at the new color scheme. If it's quite different, I'd most likely create a new theme with the new color scheme and name. I wouldn't want to change it if there are people happy with the current color scheme.

**Comment by mngshm** [comment]
Sure 👍🏻
